### PR TITLE
Introduce Grant Interface

### PR DESCRIPTION
**Pull request by AvraCodabra**
This PR introduces a new `Grant` interface to provide a standardized structure for grant-related data, facilitating improved code organization and readability. The Grant interface includes the following properties:

```typescript
export interface Grant {
  name: string;
  amount: number;
  payDate: PayDate;
  explanation?: string; // how the amount was calculated
  description?: string; // additional info about the grant
}
``` 

Currently, only the `amount` property is utilized in existing functions, but this sets the foundation for potential future refactoring.

Additionally, a new file named **`grants.ts`** has been created to encapsulate data for each grant, enhancing code readability and comparability to legal specifications.

### Changes Made:

1. **Introducing Grant Interface**:
Created a new Grant interface with standardized properties.

2. **Encapsulating Grant Data**:
Created a new file `grants.ts` to centralize and organize grant-related data.
Moved grant definitions to grants.ts for better code organization.

### CODE REVIEW

**Comment by wiserdor** [comment]
amazing work thank you!
please fix all comments as `yarn build` is giving errors and `yarn vite` site is not working

**Comment by wiserdor** [comment]
please be aware that:
- you completely abandoned the original calculator calculations and this is a pretty big change that we prefer not to touch. we are working closely with the military on those calculations so please use them as the source of truth.

**Comment by AvraCodabra** [comment]
It was intentional as some of the current calculations contained mistakes.

But you are right, it's a big change so I will change it now to reference the original calculations and create a separate PR for the calculation fix.

**Comment by AvraCodabra** [comment]
@wiserdor on second thought, 

As this pr align all grants in a very readable way => function per grant that appear in the [miluim site](https://www.miluim.idf.il/articles-list/%D7%9E%D7%93%D7%99%D7%A0%D7%99%D7%95%D7%AA-%D7%9E%D7%A2%D7%A0%D7%A7%D7%99%D7%9D-%D7%9C%D7%9E%D7%A9%D7%A8%D7%AA%D7%99-%D7%9E%D7%99%D7%9C%D7%95%D7%90%D7%99%D7%9D-%D7%91%D7%9E%D7%9C%D7%97%D7%9E%D7%AA-%D7%97%D7%A8%D7%91%D7%95%D7%AA-%D7%91%D7%A8%D7%96%D7%9C/) - it took a few days to translate the site into functions.
(I also added more grants that were missing in the current calculation) 
I highly recommend reviewing the `grants.ts` file with your team and set it as the new source of truth if possible.

I fixed the build issue,
if you receive an error of unused function - it's a function of a new grant..
you can still run local using `npm run dev`

LMKWYT ✌️

**Pull request closed without merging**
